[project]
name = "wolves_in_silico"
version = "0.0.1"
dependencies = [
    "numpy",
    "matplotlib",
]

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"
include-package-data = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]