[tool.poetry]
name = "wolves in silico"
version = "0.1.0"
description = ""
authors = ["Margriet Palm"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.5.3"
numpy = "^1.23.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
flake9 = "^3.8.3.post2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
