[project]
name = "Wolves_in_Silico"
version = "0.0.1"
dependencies = [
    "numpy",
    "matplotlib",
]

[tool.flakeheaven]
exclude = ["venv", "wolves_in_silico.egg-info", "build/*", ".git/*", ".tox"]
format = "grouped"
max_line_length = 120

[tool.flakeheaven.plugins]
flake8-class-attributes-order = ["+*"]
flake8-comprehensions = ["+*"]
flake8-print = ["+*"]
pep8-naming = ["+*"]

[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39

[testenv]
deps =
    flakeheaven
    pytest
    pytest-cov
commands =
    flakeheaven lint
    pytest --disable-warnings --cov-report term

[run]
omit = .tox/*,venv/*,tests/*,htmlcov*,analyses*

"""